name = "Packin' DET"
author = "JaredSheep & Co."
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df7834cf4a016d2f37bd6d5c27d4444e6748e5ed98d5c136546208b52bf814a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
