name = "Packin' DET"
author = "JaredSheep & Co."
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c615bec578b07fd3477f770e378acda68e0bb4d28b5e91a58c170715502c3e"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
