name = "Packin' DET"
author = "JaredSheep & Co."
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efbed7c880fe98b6a1b5e6d4c0e493f223b62ad9f916f29225cdd437528b5670"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
