name = "Packin' DET"
author = "JaredSheep & Co."
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "485f269ad2239e9d1122ab9a0b85b3b6bbba56bbf0f6242d3b25fc92180c0004"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
