name: export-and-release

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  export-and-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Version
      - run: |
            echo "MODPACK_VERSION=$(cat version.txt)" >> $GITHUB_ENV
            echo "New version is $MODPACK_VERSION"

      - name: Export to CurseForge 
        run: ./packwiz cf export

      - name: Create Release
      - uses: ncipollo/release-action@v1.12.0
        with:
            commit: "master"
            tag: "$MODPACK_VERSION"
            artifacts: "*.zip"
            generateReleaseNotes: true
            makeLatest: true
